name: データ取得ワークフロー
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 4-16 * * 3'
    - cron: '0 */6 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4
        with:
          ref: htdocs
      - name: データのダウンロード
        run: |
          pip install -r ./collect-move/requirements.txt
          python ./collect-move/src/main/
      - name: 差分チェック
        run: |
          if ! diff -qr ./tmp/ ./docs/resource/data/ --exclude=metadata.json | grep -q ".json"; then
            echo "差分なし"
            echo "FLOW_STOP=1" >> $GITHUB_ENV
            exit 0
          fi
          echo "FLOW_STOP=0" >> $GITHUB_ENV
      - name: JSONをコピー
        if: ${{ env.FLOW_STOP == '0' }}
        run: |
          rsync -av --delete --include="*.json" --exclude="*"  ./tmp/ ./docs/resource/data/
      - name: 変更をコミット
        if: ${{ env.FLOW_STOP == '0' }}
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git add .
          git commit -m "JSONをコミット"
          git push origin htdocs
